---
version: '3'

services:
  redis:
    image: redis:alpine
    environment:
      - DOMAIN_NAME=redis.${BASEHOST:-wordpress.docker}

  mysql:
    image: mysql:${MYSQLVERSION:-5.7}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-toor}
      - DOMAIN_NAME=mysql.${BASEHOST:-wordpress.docker}
    command: --innodb-doublewrite=0

  mailcatcher:
    image: mailhog/mailhog
    environment:
      - DOMAIN_NAME=mailcatcher.${BASEHOST:-wordpress.docker}

  application:
    image: dockerwest/php-wordpress:${PHPVERSION:-7.1}
    environment:
      - C_UID=${C_UID:-1000}
      - C_GID=${C_GID:-1000}
      - DEVELOPMENT=${DEVELOPMENT:-1}
    volumes:
      - ${APPLICATION:-../application}:/phpapp
    links:
      - mysql
      - redis
      - mailcatcher

  nginx:
    image: dockerwest/nginx-wordpress:${NGINXVERSION:-stable}
    environment:
      - VIRTUAL_HOST=${BASEHOST:-wordpress.docker},${EXTRAHOSTS}
    volumes:
      - ${APPLICATION:-../application}:/phpapp
    links:
      - application
